"""
OBM — Opening Bell Model strategy engine.
Replicates Fede Esses' intraday NQ/ES futures strategy.

Pre-session routine (before 9:30):
  - Load 15m + 5m bars to map swing highs/lows and EQH/EQL
  - These become the DOL targets and liquidity sweep triggers

Entry flow:
  1. 09:30–09:45: wait for price to sweep a pre-session high or low (liquidity grab)
  2. Confirm SMT divergence between NQ and ES at the sweep point
  3. Wait for ChoCh on 1m/30s after the sweep
  4. Enter on retest of the FVG/OB generated by that ChoCh impulse

Scale-in flow (100% structural — no time/distance rule):
  - Condition: initial trade is open and BE is active
  - Trigger: on 1m/30s, price forms a new FVG, IFVG, or OB in trade direction
  - Confirmation: price retraces INTO that zone AND shows rejection
    (bullish rejection = close > open on retest bar; bearish = close < open)
  - Action: add scale lot (0.3% risk)
  - SL management: move SL of BOTH legs to below/above the new structural
    low/high that protected the scale-in entry

Exit flow:
  - SL: behind the OB or swept level (technical)
  - BE: once price advances by 50% of the distance to TP
  - TP: nearest unswept EQH (longs) or EQL (shorts) from pre-session map
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from datetime import time
from enum import Enum
from typing import Optional
import pandas as pd

from trader.smc.fvg import FVG, FVGType, detect_fvgs, update_fvg_status, nearest_fvg
from trader.smc.order_blocks import OrderBlock, OBType, detect_order_blocks, update_ob_status, nearest_ob
from trader.smc.smt import SMTSignal, SMTType, detect_smt_divergence, latest_smt
from trader.smc.structure import (
    StructureEvent, StructureType, detect_structure, latest_choch, detect_local_choch,
)
from trader.smc.liquidity import (
    PreSessionLevels, LiquidityLevel,
    build_presession_levels, mark_swept_levels, get_dol_target,
)

logger = logging.getLogger(__name__)

SESSION_OPEN = time(9, 30)
SESSION_CLOSE = time(16, 0)
OBM_WINDOW_END = time(10, 30)   # extended: Fede takes setups up to ~10:30 if clean


class TradeDirection(Enum):
    LONG = "long"
    SHORT = "short"


class TradeState(Enum):
    WAITING = "waiting"
    SETUP_FOUND = "setup_found"
    IN_TRADE = "in_trade"
    SCALED_IN = "scaled_in"
    CLOSED = "closed"


@dataclass
class ScaleLeg:
    entry_price: float
    size: float
    stop_loss: float          # SL specific to this leg
    entry_time: pd.Timestamp
    entry_zone_bottom: float  # zone bottom that triggered scale-in
    entry_zone_top: float


@dataclass
class Trade:
    direction: TradeDirection
    entry_price: float
    stop_loss: float          # unified SL (moves on scale-in)
    take_profit: float        # DOL target
    entry_time: pd.Timestamp
    size: float
    state: TradeState = TradeState.IN_TRADE

    scale: Optional[ScaleLeg] = None
    be_activated: bool = False
    pnl: float = 0.0
    exit_price: Optional[float] = None
    exit_time: Optional[pd.Timestamp] = None
    exit_reason: str = ""

    @property
    def total_size(self) -> float:
        return self.size + (self.scale.size if self.scale else 0.0)

    @property
    def avg_entry(self) -> float:
        if self.scale is None:
            return self.entry_price
        total = self.entry_price * self.size + self.scale.entry_price * self.scale.size
        return total / self.total_size

    def __repr__(self) -> str:
        return (
            f"Trade({self.direction.value} | entry={self.entry_price:.2f} "
            f"SL={self.stop_loss:.2f} TP={self.take_profit:.2f} "
            f"size={self.total_size:.4f} state={self.state.value})"
        )


@dataclass
class OBMSetup:
    direction: TradeDirection
    smt_signal: SMTSignal
    choch_event: StructureEvent
    entry_fvg: Optional[FVG]
    sweep_level: float
    dol_target: float
    formed_at: pd.Timestamp
    valid: bool = True


class OBMStrategy:
    """
    Stateful OBM engine. Call update() on each new 1m bar.
    Manages one trade at a time.
    """

    def __init__(
        self,
        initial_risk_pct: float = 0.005,
        scale_risk_pct: float = 0.003,
        daily_loss_limit: float = 0.02,
        swing_lookback: int = 3,          # lowered from 5: needs fewer bars to form a swing
        smt_tolerance: float = 0.004,     # raised from 0.002: less strict divergence filter
        fvg_atr_multiplier: float = 0.25,
        be_trigger_ratio: float = 0.5,
    ):
        self.initial_risk_pct = initial_risk_pct
        self.scale_risk_pct = scale_risk_pct
        self.daily_loss_limit = daily_loss_limit
        self.swing_lookback = swing_lookback
        self.smt_tolerance = smt_tolerance
        self.fvg_atr_multiplier = fvg_atr_multiplier
        self.be_trigger_ratio = be_trigger_ratio

        self.state = TradeState.WAITING
        self.active_trade: Optional[Trade] = None
        self.active_setup: Optional[OBMSetup] = None
        self.trade_history: list[Trade] = []

        self._daily_pnl: float = 0.0
        self._daily_halted: bool = False
        self._current_date: Optional[pd.Timestamp] = None

        # Pre-session levels — rebuilt each day
        self._presession: Optional[PreSessionLevels] = None

        # Rolling SMC state
        self._nq_fvgs: list[FVG] = []
        self._smt_signals: list[SMTSignal] = []
        self._structure_events: list[StructureEvent] = []

        # Buffer of recent 1m bars for micro-structure analysis
        self._nq_buffer: list[pd.Series] = []
        self._es_buffer: list[pd.Series] = []
        self._buffer_ts: list[pd.Timestamp] = []
        self._buffer_max = 200

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def initialize(
        self,
        nq_hist_1m: pd.DataFrame,
        es_hist_1m: pd.DataFrame,
        nq_hist_15m: pd.DataFrame,
        es_hist_15m: pd.DataFrame,
        nq_hist_5m: pd.DataFrame,
        session_date: pd.Timestamp,
    ) -> None:
        """
        Seed SMC state + build pre-session levels for the given trading day.
        Call once before the session starts.
        """
        nq_aligned, es_aligned = _align(nq_hist_1m, es_hist_1m)

        self._nq_fvgs = detect_fvgs(
            nq_aligned, "1m", atr_multiplier=self.fvg_atr_multiplier
        )
        self._smt_signals = detect_smt_divergence(
            nq_aligned, es_aligned, self.swing_lookback, self.smt_tolerance
        )
        self._structure_events = detect_structure(nq_aligned, "1m", self.swing_lookback)
        update_fvg_status(self._nq_fvgs, nq_aligned)

        # Pre-populate buffer with the last _buffer_max bars of seed data
        # so the rolling window already has context when the first live bar arrives
        tail = nq_aligned.iloc[-self._buffer_max:]
        es_tail = es_aligned.iloc[-self._buffer_max:]
        for i in range(len(tail)):
            self._push_buffer(tail.index[i], tail.iloc[i], es_tail.iloc[i])

        # Build pre-session levels from 15m + 5m
        self._presession = build_presession_levels(
            df_15m=nq_hist_15m,
            df_5m=nq_hist_5m,
            session_date=session_date,
            swing_lookback=self.swing_lookback,
        )
        logger.info(
            "Initialized | FVGs=%d SMT=%d structure=%d | pre-session highs=%d lows=%d",
            len(self._nq_fvgs), len(self._smt_signals), len(self._structure_events),
            len(self._presession.highs), len(self._presession.lows),
        )

    def update(
        self,
        ts: pd.Timestamp,
        nq_bar: pd.Series,
        es_bar: pd.Series,
        account_value: float,
    ) -> Optional[dict]:
        """
        Process one new 1m bar. Returns an order dict or None.

        Order dict:
            action: "open_long" | "open_short" | "scale_in_long" | "scale_in_short"
                    | "close" | "move_sl" | "daily_halt"
            price, size, sl, tp, reason
        """
        self._reset_daily_if_needed(ts)

        if self._daily_halted:
            return {"action": "daily_halt", "reason": "daily loss limit reached"}

        bar_time = ts.tz_convert("America/New_York").time()

        # Rolling buffer for micro-structure detection
        self._push_buffer(ts, nq_bar, es_bar)

        # Update FVG fill status on each bar
        bar_df = _bar_to_df(ts, nq_bar)
        update_fvg_status(self._nq_fvgs, bar_df)

        # Update pre-session level sweep tracking
        if self._presession:
            mark_swept_levels(self._presession, bar_df)

        # Manage open trade first (SL / BE / scale-in / TP)
        if self.active_trade and self.active_trade.state in (
            TradeState.IN_TRADE, TradeState.SCALED_IN
        ):
            order = self._manage_trade(ts, nq_bar, account_value)
            if order:
                return order

        # Look for new OBM setups only during the opening window
        if self.active_trade is None and SESSION_OPEN <= bar_time <= OBM_WINDOW_END:
            order = self._scan_for_setup(ts, nq_bar, es_bar, account_value)
            if order:
                return order

        # Check if a pending setup has triggered an entry
        if self.active_setup and self.active_setup.valid and self.active_trade is None:
            order = self._check_entry_trigger(ts, nq_bar, account_value)
            if order:
                return order

        return None

    # ------------------------------------------------------------------
    # Setup detection
    # ------------------------------------------------------------------

    def _scan_for_setup(
        self,
        ts: pd.Timestamp,
        nq_bar: pd.Series,
        es_bar: pd.Series,
        account_value: float,
    ) -> Optional[dict]:
        if self._presession is None:
            return None

        # Detect new SMT divergence from the rolling buffer
        nq_buf_df, es_buf_df = self._buffer_as_df()
        if nq_buf_df is None:
            return None

        new_smt = detect_smt_divergence(nq_buf_df, es_buf_df, self.swing_lookback, self.smt_tolerance)
        self._smt_signals.extend(new_smt)

        # Look back up to 30 bars (~30 min) for a valid SMT signal
        smt = latest_smt(self._smt_signals, before=ts, max_bars_ago=30, bar_interval_minutes=1)
        if smt is None:
            return None

        # Pre-session level filter: relaxed to 1% tolerance
        if not self._smt_near_presession_level(smt, tolerance_pct=0.01):
            return None

        # Detect local ChoCh after the sweep (micro-reversal on 1m/30s)
        # Uses rolling window instead of global trend — matches Fede's actual entry trigger
        local_chochs = detect_local_choch(nq_buf_df, "1m", window=15, swing_lookback=2)
        self._structure_events.extend(local_chochs)
        choch = latest_choch(self._structure_events, before=ts, max_bars_ago=30, bar_interval_minutes=1)
        if choch is None:
            return None

        direction = (
            TradeDirection.LONG if smt.type == SMTType.BULLISH
            else TradeDirection.SHORT
        )

        # ChoCh must align with SMT direction
        if direction == TradeDirection.LONG and choch.type != StructureType.CHOCH_BULLISH:
            return None
        if direction == TradeDirection.SHORT and choch.type != StructureType.CHOCH_BEARISH:
            return None

        # Find FVG created by the ChoCh impulse (entry zone)
        fvg_type = FVGType.BULLISH if direction == TradeDirection.LONG else FVGType.BEARISH
        new_fvgs = detect_fvgs(nq_buf_df, "1m", atr_multiplier=self.fvg_atr_multiplier)
        self._nq_fvgs.extend(new_fvgs)
        entry_fvg = nearest_fvg(nq_bar["close"], self._nq_fvgs, fvg_type)

        # DOL from pre-session liquidity map
        dol = get_dol_target(direction.value, nq_bar["close"], self._presession)

        self.active_setup = OBMSetup(
            direction=direction,
            smt_signal=smt,
            choch_event=choch,
            entry_fvg=entry_fvg,
            sweep_level=smt.swept_level,
            dol_target=dol,
            formed_at=ts,
        )
        logger.info(
            "Setup: %s | sweep=%.2f DOL=%.2f | SMT=%s ChoCh=%s",
            direction.value, smt.swept_level, dol, smt, choch,
        )
        return None

    def _check_entry_trigger(
        self,
        ts: pd.Timestamp,
        nq_bar: pd.Series,
        account_value: float,
    ) -> Optional[dict]:
        setup = self.active_setup
        if setup is None or not setup.valid:
            return None

        # Invalidate stale setup
        if ts > setup.formed_at + pd.Timedelta(minutes=15):
            setup.valid = False
            self.active_setup = None
            logger.info("Setup expired at %s", ts)
            return None

        price = nq_bar["close"]
        fvg = setup.entry_fvg

        if fvg is None or not fvg.contains_price(price):
            return None

        # SL is placed behind the swept level with a small buffer
        buf = setup.sweep_level * 0.0005  # 0.05% buffer
        sl = (setup.sweep_level - buf) if setup.direction == TradeDirection.LONG \
             else (setup.sweep_level + buf)

        risk_per_unit = abs(price - sl)
        if risk_per_unit == 0:
            return None

        size = (account_value * self.initial_risk_pct) / risk_per_unit

        trade = Trade(
            direction=setup.direction,
            entry_price=price,
            stop_loss=sl,
            take_profit=setup.dol_target,
            entry_time=ts,
            size=size,
            state=TradeState.IN_TRADE,
        )
        self.active_trade = trade
        self.active_setup = None
        self.state = TradeState.IN_TRADE

        action = "open_long" if setup.direction == TradeDirection.LONG else "open_short"
        logger.info("ENTRY %s @ %.2f | SL=%.2f TP=%.2f size=%.4f", action, price, sl, setup.dol_target, size)
        return {
            "action": action,
            "price": price,
            "size": size,
            "sl": sl,
            "tp": setup.dol_target,
            "reason": "FVG retest after ChoCh+SMT+liquidity sweep",
        }

    # ------------------------------------------------------------------
    # Trade management
    # ------------------------------------------------------------------

    def _manage_trade(
        self,
        ts: pd.Timestamp,
        nq_bar: pd.Series,
        account_value: float,
    ) -> Optional[dict]:
        trade = self.active_trade
        price = nq_bar["close"]
        high = nq_bar["high"]
        low = nq_bar["low"]

        # TP hit
        if trade.direction == TradeDirection.LONG and high >= trade.take_profit:
            return self._close_trade(ts, trade.take_profit, "TP — DOL reached")
        if trade.direction == TradeDirection.SHORT and low <= trade.take_profit:
            return self._close_trade(ts, trade.take_profit, "TP — DOL reached")

        # SL hit (unified SL covers all legs)
        if trade.direction == TradeDirection.LONG and low <= trade.stop_loss:
            return self._close_trade(ts, trade.stop_loss, "SL hit")
        if trade.direction == TradeDirection.SHORT and high >= trade.stop_loss:
            return self._close_trade(ts, trade.stop_loss, "SL hit")

        # Move SL to Break-Even
        if not trade.be_activated:
            tp_distance = abs(trade.take_profit - trade.entry_price)
            be_trigger = tp_distance * self.be_trigger_ratio

            if trade.direction == TradeDirection.LONG and price >= trade.entry_price + be_trigger:
                trade.stop_loss = trade.entry_price
                trade.be_activated = True
                logger.info("BE activated @ %.2f", trade.entry_price)
                return {"action": "move_sl", "price": trade.stop_loss, "size": trade.total_size,
                        "reason": "break-even"}
            elif trade.direction == TradeDirection.SHORT and price <= trade.entry_price - be_trigger:
                trade.stop_loss = trade.entry_price
                trade.be_activated = True
                logger.info("BE activated @ %.2f", trade.entry_price)
                return {"action": "move_sl", "price": trade.stop_loss, "size": trade.total_size,
                        "reason": "break-even"}

        # Scale-in: only available once BE is active and no scale has been done yet
        if trade.be_activated and trade.scale is None:
            scale_order = self._check_scale_in(ts, nq_bar, account_value, trade)
            if scale_order:
                return scale_order

        return None

    def _check_scale_in(
        self,
        ts: pd.Timestamp,
        nq_bar: pd.Series,
        account_value: float,
        trade: Trade,
    ) -> Optional[dict]:
        """
        Scale-in is 100% structural:
          1. Price must be in a new FVG/IFVG/OB in trade direction
          2. The bar must show rejection (close > open for long, close < open for short)
          3. SL of both legs moves to below/above the new structural low/high
        """
        price = nq_bar["close"]
        fvg_type = FVGType.BULLISH if trade.direction == TradeDirection.LONG else FVGType.BEARISH

        # Find a fresh FVG or IFVG in the trade direction near current price
        nq_buf_df, _ = self._buffer_as_df()
        if nq_buf_df is not None:
            new_fvgs = detect_fvgs(nq_buf_df, "1m", atr_multiplier=self.fvg_atr_multiplier)
            self._nq_fvgs.extend(new_fvgs)

        # Prefer IFVGs (stronger), then regular FVGs
        ifvgs = [f for f in self._nq_fvgs if f.inverted and f.type == fvg_type]
        fvgs = [f for f in self._nq_fvgs if not f.filled and f.type == fvg_type]

        zone: Optional[FVG] = nearest_fvg(price, ifvgs, fvg_type) or nearest_fvg(price, fvgs, fvg_type)
        if zone is None or not zone.contains_price(price):
            return None

        # Rejection confirmation: candle must close in the right direction
        is_rejection = (
            (trade.direction == TradeDirection.LONG and nq_bar["close"] > nq_bar["open"])
            or (trade.direction == TradeDirection.SHORT and nq_bar["close"] < nq_bar["open"])
        )
        if not is_rejection:
            return None

        # New structural SL: just beyond the zone that protected entry
        if trade.direction == TradeDirection.LONG:
            new_sl = zone.bottom * 0.9995   # just below the zone bottom
        else:
            new_sl = zone.top * 1.0005      # just above the zone top

        risk_per_unit = abs(price - new_sl)
        if risk_per_unit == 0:
            return None

        scale_size = (account_value * self.scale_risk_pct) / risk_per_unit

        # Update unified SL for both legs
        old_sl = trade.stop_loss
        trade.stop_loss = new_sl
        trade.scale = ScaleLeg(
            entry_price=price,
            size=scale_size,
            stop_loss=new_sl,
            entry_time=ts,
            entry_zone_bottom=zone.bottom,
            entry_zone_top=zone.top,
        )
        trade.state = TradeState.SCALED_IN

        action = "scale_in_long" if trade.direction == TradeDirection.LONG else "scale_in_short"
        zone_type = "IFVG" if zone.inverted else "FVG"
        logger.info(
            "SCALE-IN %s @ %.2f | new unified SL=%.2f (was %.2f) | size=%.4f | zone=%s",
            action, price, new_sl, old_sl, scale_size, zone_type,
        )
        return {
            "action": action,
            "price": price,
            "size": scale_size,
            "sl": new_sl,          # applies to ALL open contracts
            "tp": trade.take_profit,
            "reason": f"structural scale-in on {zone_type} retest with rejection",
        }

    def _close_trade(self, ts: pd.Timestamp, exit_price: float, reason: str) -> dict:
        trade = self.active_trade

        if trade.direction == TradeDirection.LONG:
            pnl = (exit_price - trade.entry_price) * trade.size
            if trade.scale:
                pnl += (exit_price - trade.scale.entry_price) * trade.scale.size
        else:
            pnl = (trade.entry_price - exit_price) * trade.size
            if trade.scale:
                pnl += (trade.scale.entry_price - exit_price) * trade.scale.size

        trade.pnl = pnl
        trade.exit_price = exit_price
        trade.exit_time = ts
        trade.exit_reason = reason
        trade.state = TradeState.CLOSED

        self._daily_pnl += pnl
        self.trade_history.append(trade)
        self.active_trade = None
        self.state = TradeState.WAITING

        logger.info("CLOSE %s @ %.2f | PnL=%.2f | %s", trade.direction.value, exit_price, pnl, reason)
        return {
            "action": "close",
            "price": exit_price,
            "size": trade.total_size,
            "pnl": pnl,
            "reason": reason,
        }

    # ------------------------------------------------------------------
    # Daily reset / helpers
    # ------------------------------------------------------------------

    def _reset_daily_if_needed(self, ts: pd.Timestamp) -> None:
        date = ts.normalize()
        if self._current_date is None or date > self._current_date:
            self._current_date = date
            self._daily_pnl = 0.0
            self._daily_halted = False
            # Pre-session levels are rebuilt externally via initialize() each day

    def _push_buffer(self, ts: pd.Timestamp, nq_bar: pd.Series, es_bar: pd.Series) -> None:
        self._nq_buffer.append(nq_bar)
        self._es_buffer.append(es_bar)
        self._buffer_ts.append(ts)
        if len(self._nq_buffer) > self._buffer_max:
            self._nq_buffer.pop(0)
            self._es_buffer.pop(0)
            self._buffer_ts.pop(0)

    def _buffer_as_df(self) -> tuple[Optional[pd.DataFrame], Optional[pd.DataFrame]]:
        if len(self._nq_buffer) < 15:
            return None, None
        nq_df = pd.DataFrame(self._nq_buffer, index=self._buffer_ts)
        es_df = pd.DataFrame(self._es_buffer, index=self._buffer_ts)
        return nq_df, es_df

    def _smt_near_presession_level(self, smt: SMTSignal, tolerance_pct: float = 0.01) -> bool:
        """Return True if the SMT swept level is within tolerance of a pre-session level."""
        if self._presession is None:
            return True  # no pre-session data — don't filter

        all_levels = self._presession.all_levels
        for level in all_levels:
            if abs(smt.swept_level - level.price) / level.price <= tolerance_pct:
                return True
        return False


# ------------------------------------------------------------------
# Utils
# ------------------------------------------------------------------

def _align(nq: pd.DataFrame, es: pd.DataFrame) -> tuple[pd.DataFrame, pd.DataFrame]:
    common = nq.index.intersection(es.index)
    return nq.loc[common], es.loc[common]


def _bar_to_df(ts: pd.Timestamp, bar: pd.Series) -> pd.DataFrame:
    return pd.DataFrame([bar], index=[ts])
